feat(CPNT-2249): validates newsuk ruleset

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,6 +19,13 @@ jobs:
             - run:
                   name: List installed phpcs standards
                   command: vendor/bin/phpcs -i
+            - run:
+                  name: Check if NewsUK standard is installed
+                  command: |
+                    if ! phpcs -i | grep -q "NewsUK"; then
+                      echo "Error: NewsUK PHPCS standard is not installed."
+                      exit 1
+                    fi
             - persist_to_workspace:
                   root: .
                   paths:
